---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    type: proxy
spec:
 replicas: 2
 selector: 
   matchLabels:
     type: proxy
 template:
   metadata:
      name: nginx-pod
      labels:
        type: proxy
   spec:
     containers:
      - name: myapp
        image: nginx
     affinity:
       nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms: 
             - matchExpressions:
                - key: slave2
                  operator: In
                  values:
                   - intelliqit3
...
